
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Plus } from 'lucide-react';
import { useToast } from '@/components/ui/use-toast';
import { Portfolio } from '@/lib/supabase';
import { fetchPortfolio, createPortfolioItem, updatePortfolioItem, deletePortfolioItem, reorderPortfolioItems } from '@/services/databaseService';
import PortfolioForm from './PortfolioForm';
import PortfolioList from './PortfolioList';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';

const PortfolioAdmin = () => {
  const [editingItem, setEditingItem] = useState<Portfolio | null>(null);
  const [isAdding, setIsAdding] = useState(false);
  const { toast } = useToast();
  const queryClient = useQueryClient();

  // Fetch portfolio items from database
  const { data: portfolioItems = [], isLoading, error } = useQuery({
    queryKey: ['portfolio'],
    queryFn: fetchPortfolio
  });
  
  portfolioItems.sort((a, b) => a.order - b.order);

  // Create portfolio item mutation
  const createMutation = useMutation({
    mutationFn: createPortfolioItem,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['portfolio'] });
    }
  });

  // Update portfolio item mutation
  const updateMutation = useMutation({
    mutationFn: ({ id, updates }: { id: string; updates: Partial<Portfolio> }) => 
      updatePortfolioItem(id, updates),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['portfolio'] });
    }
  });

  // Delete portfolio item mutation
  const deleteMutation = useMutation({
    mutationFn: deletePortfolioItem,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['portfolio'] });
    }
  });

  // Reorder portfolio items mutation
  const reorderMutation = useMutation({
    mutationFn: reorderPortfolioItems,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['portfolio'] });
      toast({
        title: "Order updated",
        description: "Portfolio items have been reordered successfully",
      });
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: `Failed to reorder items: ${error}`,
        variant: "destructive"
      });
    }
  });

  const handleEdit = (item: Portfolio) => {
    setEditingItem({ ...item });
    setIsAdding(false);
  };

  const handleAdd = () => {
    // Changed: Remove the ID generation here since Supabase will generate the UUID
    const newItem = {
      id: '', // Empty ID, will be generated by Supabase
      title: "",
      category: "Web Design",
      imageUrl: "",
      description: "",
      link: ""
    };
    setEditingItem(newItem);
    setIsAdding(true);
  };

  const handleSave = (item: Portfolio) => {
    if (isAdding) {
      // For new items, don't include the id field
      const { id, ...itemWithoutId } = item;
      createMutation.mutate(itemWithoutId as Portfolio);
    } else {
      updateMutation.mutate({ 
        id: item.id, 
        updates: item 
      });
    }
    setEditingItem(null);
    setIsAdding(false);
  };

  const handleCancel = () => {
    setEditingItem(null);
    setIsAdding(false);
  };

  const handleDelete = (id: string) => {
    const itemToDelete = portfolioItems.find(item => item.id === id);
    
    if (window.confirm(`Are you sure you want to delete "${itemToDelete?.title}"?`)) {
      deleteMutation.mutate(id);
    }
  };

  const handleReorder = (newOrder: Portfolio[]) => {
    reorderMutation.mutate(newOrder);
  };

  if (isLoading) {
    return <div className="flex justify-center py-10">
      <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-agency-purple"></div>
    </div>;
  }

  if (error) {
    return <div className="text-red-500 p-4">
      Error loading portfolio items. Please try again later.
    </div>;
  }

  return (
    <div>
      <div className="flex justify-between items-center mb-6">
        <div>
          <h1 className="text-2xl font-bold text-white">Portfolio Management</h1>
          <p className="text-gray-400">Add, edit, or remove portfolio items from your website</p>
        </div>
        <Button 
          onClick={handleAdd}
          className="bg-gradient-to-r from-agency-purple to-agency-blue hover:from-agency-blue hover:to-agency-purple"
        >
          <Plus size={16} className="mr-2" />
          Add Project
        </Button>
      </div>

      {editingItem ? (
        <Card className="glass-card p-6 mb-8">
          <h2 className="text-xl font-bold text-white mb-4">
            {isAdding ? "Add New Project" : "Edit Project"}
          </h2>
          
          <PortfolioForm 
            isAdding={isAdding}
            editingItem={editingItem}
            onSave={handleSave}
            onCancel={handleCancel}
          />
        </Card>
      ) : null}

      <PortfolioList 
        portfolioItems={portfolioItems}
        onEdit={handleEdit}
        onDelete={handleDelete}
        onReorder={handleReorder}
      />
    </div>
  );
};

export default PortfolioAdmin;
