// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elzggwzlabarqkmjywaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsemdnd3psYWJhcnFrbWp5d2FmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk2MzM2MzEsImV4cCI6MjA3NTIwOTYzMX0.KO-ERCy49q7283AR8OZryAZAqoOqk4uwcLcTKCAGBds";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);